from __future__ import annotations

from collections import defaultdict


def normalize_label(label: str) -> str:
    return " ".join(label.strip().lower().replace("_", " ").split())


COARSE_GROUPS: dict[str, str] = {
    "person": "human",
    "rider": "human",
    "bicycle": "vehicle-light",
    "motorcycle": "vehicle-light",
    "car": "vehicle-road",
    "truck": "vehicle-road",
    "bus": "vehicle-road",
    "train": "vehicle-rail",
    "airplane": "vehicle-air",
    "boat": "vehicle-water",
    "traffic light": "traffic-control",
    "traffic sign": "traffic-control",
    "stop sign": "traffic-control",
    "parking meter": "traffic-control",
    "bench": "street-furniture",
    "bird": "animal",
    "cat": "animal",
    "dog": "animal",
    "horse": "animal",
    "sheep": "animal",
    "cow": "animal",
    "elephant": "animal",
    "bear": "animal",
    "zebra": "animal",
    "giraffe": "animal",
    "backpack": "personal-item",
    "umbrella": "personal-item",
    "handbag": "personal-item",
    "tie": "personal-item",
    "suitcase": "personal-item",
    "frisbee": "sports-gear",
    "skis": "sports-gear",
    "snowboard": "sports-gear",
    "sports ball": "sports-gear",
    "kite": "sports-gear",
    "baseball bat": "sports-gear",
    "baseball glove": "sports-gear",
    "skateboard": "sports-gear",
    "surfboard": "sports-gear",
    "tennis racket": "sports-gear",
    "bottle": "container",
    "wine glass": "container",
    "cup": "container",
    "fork": "utensil",
    "knife": "utensil",
    "spoon": "utensil",
    "bowl": "container",
    "banana": "food",
    "apple": "food",
    "sandwich": "food",
    "orange": "food",
    "broccoli": "food",
    "carrot": "food",
    "hot dog": "food",
    "pizza": "food",
    "donut": "food",
    "cake": "food",
    "chair": "furniture",
    "couch": "furniture",
    "potted plant": "furniture",
    "bed": "furniture",
    "dining table": "furniture",
    "toilet": "bathroom-fixture",
    "tv": "electronics",
    "laptop": "electronics",
    "mouse": "electronics",
    "remote": "electronics",
    "keyboard": "electronics",
    "cell phone": "electronics",
    "microwave": "appliance",
    "oven": "appliance",
    "toaster": "appliance",
    "sink": "appliance",
    "refrigerator": "appliance",
    "book": "media",
    "clock": "home-item",
    "vase": "home-item",
    "scissors": "tool",
    "teddy bear": "toy",
    "hair drier": "appliance",
    "toothbrush": "bathroom-item",
}

# Fine variants are lexical refinements that still map back to the same canonical class.
FINE_VARIANTS: dict[str, list[str]] = {
    "person": ["adult person", "walking pedestrian", "standing person"],
    "rider": ["bike rider", "motor rider"],
    "car": ["sedan", "hatchback", "road car"],
    "truck": ["cargo truck", "pickup truck", "heavy truck"],
    "bus": ["city bus", "passenger bus"],
    "train": ["rail train", "passenger train"],
    "traffic light": ["road signal light", "intersection traffic light"],
    "traffic sign": ["road sign", "street sign"],
    "bicycle": ["road bicycle", "city bicycle"],
    "motorcycle": ["street motorcycle", "motorbike"],
    "dog": ["pet dog", "canine"],
    "cat": ["domestic cat", "feline"],
    "airplane": ["passenger airplane", "jet aircraft"],
    "boat": ["watercraft", "small boat"],
    "chair": ["seat chair", "armchair"],
    "couch": ["sofa couch", "living room sofa"],
    "tv": ["television monitor", "tv screen"],
    "cell phone": ["smartphone", "mobile phone"],
    "laptop": ["notebook computer", "portable laptop"],
    "bottle": ["drink bottle", "plastic bottle"],
    "cup": ["drinking cup", "coffee cup"],
    "sports ball": ["soccer ball", "round sports ball"],
    "backpack": ["travel backpack", "school backpack"],
    "book": ["paperback book", "hardcover book"],
}

COARSE_ALIASES: dict[str, list[str]] = {
    "human": ["human", "person group"],
    "vehicle-road": ["road vehicle", "street vehicle"],
    "vehicle-light": ["two-wheel vehicle", "light vehicle"],
    "vehicle-rail": ["rail vehicle", "train vehicle"],
    "vehicle-air": ["air vehicle", "aircraft"],
    "vehicle-water": ["water vehicle", "boat craft"],
    "traffic-control": ["traffic control", "road control sign"],
    "animal": ["animal", "fauna"],
    "food": ["food item", "edible item"],
    "furniture": ["furniture", "house furniture"],
    "electronics": ["electronic device", "electronics"],
    "sports-gear": ["sports equipment", "sports gear"],
}


def build_term_to_classes(class_to_term: dict[str, str]) -> dict[str, list[str]]:
    inv: dict[str, list[str]] = defaultdict(list)
    for cls, term in class_to_term.items():
        inv[term].append(cls)
    return {k: sorted(v) for k, v in inv.items()}
